# Generated by Django 4.2 on 2023-05-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_events_logs_room_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Tel', 'Телефон'), ('Mail', 'Электронная почта'), ('Href', 'Обычная ссылка'), ('None', 'Без ссылки')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('stopcheck', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
        migrations.AddField(
            model_name='room',
            name='href_img',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social_media',
            name='href_img',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='href',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
