# Generated by Django 4.2 on 2023-05-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_contact_manager_price_rename_events_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='href_img',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
