# Generated by Django 4.2 on 2023-05-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_manager_href_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
