# Generated by Django 4.2 on 2023-06-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
