# Generated by Django 4.2 on 2023-06-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_category_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='href_img',
            field=models.ImageField(blank=True, upload_to='rooms/%Y/%m/%d'),
        ),
    ]
